name: Static Analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: Run PHP Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Clone SymconStubs
        run: git clone https://github.com/symcon/SymconStubs.git ../_ips-stubs

      - name: Install PHPStan
        run: |
          wget https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar -O phpstan.phar
          chmod +x phpstan.phar

      - name: Run PHPStan
        run: php phpstan.phar analyse --configuration=phpstan.neon
